Create path control
Terralego/terra-front pull request #236
Opened 2021-01-13 14:38 UTC by dtrucs

2021-01-14 11:09 UTC, jrmi commented on src/stories/modules/Map/MapControls.stories.js
> +const accessToken = 'pk.eyJ1IjoibWFraW5hY29ycHVzIiwiYSI6ImNqY3E4ZTNwcTFta3ozMm80d2xzY29wM2MifQ.Nwl_FHrWAIQ46s_lY0KNiQ';
PLS ;-)

2021-01-18 13:51 UTC, jrmi commented on src/modules/Map/Map/components/PathControl/PathControl.js
> +    // this.PathControl.onRemove = function () {
Want to keep this ?

2021-01-18 13:52 UTC, jrmi commented on src/modules/Map/Map/components/PathControl/PathControl.test.js
> +  it('Should remove 8 others listeners', () => {
8 or 3 ?

2021-01-18 13:56 UTC, jrmi reviewed
Some minor things to review

2021-02-10 14:12 UTC, jrmi commented on src/modules/Map/Map/withMap.js
> +const isDrawLayer = layer => layer.id.startsWith('gl-draw') || layer.id.startsWith('gl-pathControl');
Can you make it configurable by a props, default to the current list of to values ?

2021-02-10 14:12 UTC, jrmi approved these changes

2021-02-10 14:12 UTC, jrmi requested changes
Minor change if possible

2021-02-11 10:48 UTC, dtrucs commented on src/modules/Map/Map/withMap.js
> +const isDrawLayer = layer => layer.id.startsWith('gl-draw') || layer.id.startsWith('gl-pathControl');
Workaround found by using `map.weightAttributionHooks`

2021-02-11 11:30 UTC, jrmi approved these changes

2021-02-11 11:35 UTC, merged