Add a distance measure map control
Terralego/terra-front pull request #356
Opened 2023-09-08 07:32 UTC by CFarcy

2023-09-08 07:46 UTC, mabhub requested changes

2023-09-08 07:46 UTC, mabhub commented on src/modules/Map/Map/components/MeasureControl/index.js
> +          {!(length || area) && 'Commencez à tracer'}
We should maybe add translation function (`t()`) for each UI texts and use translation keys

2023-09-08 07:51 UTC, CFarcy commented on src/modules/Map/Map/components/MeasureControl/index.js
> +          {!(length || area) && 'Commencez à tracer'}
Yes, very good idea

2023-09-08 12:02 UTC, Bo-Duke approved these changes

2023-09-08 12:02 UTC, Bo-Duke commented on src/modules/Map/Map/components/MeasureControl/index.js
> +  }
Maybe leave console.error uncommented or remove it? Idk, it feels like an oversight when it may not be

2023-09-12 09:19 UTC, mabhub approved these changes

2023-09-12 09:20 UTC, CFarcy commented
Need https://github.com/Terralego/TerraVisu/pull/354 to be merged from now on to work.

2023-09-12 09:38 UTC, Bo-Duke approved these changes

2023-09-12 11:59 UTC, merged